name: "Lint"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.run/**'
      - 'docs/**'
      - '*.md'

  pull_request:
    branches:
      - main
    types: [ opened, synchronize ]
    paths-ignore:
      - '.run/**'
      - 'docs/**'
      - '*.md'

jobs:
  lint:
    name: "Run linter"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
          args: --timeout=3m
          skip-cache: false